# Generated by Django 4.2.17 on 2025-01-10 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0013_alter_project_approvals'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=255, verbose_name='作業内容')),
                ('is_completed', models.BooleanField(default=False, verbose_name='対応済')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todos', to='order.company', verbose_name='会社')),
            ],
        ),
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255, verbose_name='問い合わせ分類')),
                ('question', models.TextField(verbose_name='質問内容')),
                ('question_date', models.DateField(verbose_name='質問日')),
                ('answer_date', models.DateField(blank=True, null=True, verbose_name='回答日')),
                ('answer', models.TextField(blank=True, null=True, verbose_name='回答内容')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='order.company', verbose_name='会社')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='order.project', verbose_name='プロジェクト')),
            ],
        ),
    ]
